# Generated by Django 4.0.4 on 2022-05-22 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='время создания'),
        ),
    ]
